### ISSUE TITLE
[Suggestion] Add support to encode hex directly

### ISSUE THREAD

**Issue by ElfSundae** [tuupola/base62#5]
```php
$hex = '123456abcdef';
Base62::encode($hex);  // "JngPBzse6O99qumM"
Base62::encode(hex2bin($hex)); // "5gOMRIbf"
```

I think it is better to add `encodeHex` and `decodeHex` methods, then we can encode hex directly like `Base62::encodeHex($hex)`. And for internal, we may call `encodeHex` for string encoding like:

```
public function encodeHex($data)
{
    return ctype_xdigit($data) ? gmp_strval(gmp_init($data, 16), 62) : '';
}

public function encode($data, $integer = false)
{
    if (is_integer($data) || true === $integer) {
        return gmp_strval(gmp_init($data, 10), 62);
    }

    return $this->encodeHex(bin2hex($data));
}
```

**Comment by tuupola** [comment]
Adding helper functions for different possible encodings is unnecessary. The example you posted is short and concise.

```php
Base62::encode(hex2bin($hex));
```

**Comment by ElfSundae** [comment]
Then for hex there are two unnecessary convert ?

https://github.com/tuupola/base62/blob/master/src/Base62/GmpEncoder.php#L36

**Comment by tuupola** [comment]
That is lesser evil than having convenience method for each numerical system.

**Comment by ElfSundae** [comment]
OK.
